using SteelSeriesAPI.Sonar.Enums;

namespace SteelSeriesAPI.Sonar.Models;

/// <summary>An audio device known to Sonar.</summary>
/// <param name="Id">
/// The Windows device identifier, used by redirection routes.
/// WARNING: Sonar virtual device ids are regenerated by GG updates - never persist them.
/// </param>
/// <param name="Name">The human-readable device name (e.g. "Haut-parleurs (High Definition Audio Device)").</param>
/// <param name="DataFlow">Whether this is an output (render) or input (capture) device.</param>
/// <param name="IsSonarVirtual">True for the virtual devices created by Sonar itself (Gaming, Chat, Media...).</param>
/// <param name="SonarChannel">For Sonar virtual devices, the channel they carry; null for physical devices.</param>
public sealed record AudioDevice(
    string Id,
    string Name,
    AudioDataFlow DataFlow,
    bool IsSonarVirtual,
    Channel? SonarChannel);