<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>SteelSeriesAPI</RootNamespace>
    </PropertyGroup>

    <PropertyGroup Label="NuGet">
        <PackageId>Steelseries-NET-API</PackageId>
        <Version>2.0.0-alpha.1</Version>
        <Authors>DataNext</Authors>
        <Description>Unofficial .NET library to control SteelSeries GG (Sonar)</Description>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/DataNext27/SteelSeries-NET-API</RepositoryUrl>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

</Project>
