using System.Text.Json;
using SteelSeriesAPI.Core;
using SteelSeriesAPI.Sonar.Enums;
using SteelSeriesAPI.Sonar.Models;

namespace SteelSeriesAPI.Sonar.Managers;

/// <inheritdoc />
internal sealed class AppRoutingManager : IAppRoutingManager
{
    private readonly ISonarTransport _transport;

    internal AppRoutingManager(ISonarTransport transport) => _transport = transport;

    /// <inheritdoc />
    public async Task<IReadOnlyList<DeviceRouting>> GetRoutingsAsync(CancellationToken ct = default)
    {
        using var doc = await _transport.GetAsync(SonarRoutes.AudioDeviceRouting, ct).ConfigureAwait(false);
        return ParseRoutings(doc.RootElement);
    }

    /// <inheritdoc />
    public async Task RouteAppAsync(int processId, Channel channel, CancellationToken ct = default)
    {
        // Device ids are regenerated by GG updates: resolve the channel's device at call time.
        var routings = await GetRoutingsAsync(ct).ConfigureAwait(false);

        var target = routings.FirstOrDefault(r =>
            r.Channel == channel && r.DataFlow == AudioDataFlow.Render);

        if (target is null)
            throw new SonarResponseException(
                $"No render device found for channel '{channel}' in the routing state.");

        await RouteAppAsync(processId, target.DeviceId, AudioDataFlow.Render, ct).ConfigureAwait(false);
    }

    /// <inheritdoc />
    public Task RouteAppAsync(int processId, string deviceId, AudioDataFlow dataFlow, CancellationToken ct = default)
    {
        if (processId <= 0)
            throw new ArgumentOutOfRangeException(nameof(processId), processId,
                "Process id must be a positive number.");
        if (string.IsNullOrWhiteSpace(deviceId))
            throw new ArgumentException("Device id must not be empty.", nameof(deviceId));

        return _transport.PutAsync(SonarRoutes.SetAppRouting(dataFlow, deviceId, processId), ct);
    }

    /// <summary>Parses the AudioDeviceRouting array.</summary>
    internal static IReadOnlyList<DeviceRouting> ParseRoutings(JsonElement root)
    {
        var result = new List<DeviceRouting>();
        if (root.ValueKind != JsonValueKind.Array) return result;

        foreach (var entry in root.EnumerateArray())
        {
            if (ParseRouting(entry) is { } routing) result.Add(routing);
        }

        return result;
    }
    
    internal static DeviceRouting? ParseRouting(JsonElement entry) 
    {
        string? deviceId = entry.GetStringOrNull("deviceId");
        if (deviceId is null) return null;

        AudioDataFlow? dataFlow = entry.GetStringOrNull("dataFlow") switch
        {
            "render" => AudioDataFlow.Render,
            "capture" => AudioDataFlow.Capture,
            _ => null
        };
        if (dataFlow is null) return null;

        string role = entry.GetStringOrNull("role") ?? "none";

        var sessions = new List<AudioSessionInfo>();
        if (entry.TryGetProperty("audioSessions", out var sessionArray) &&
            sessionArray.ValueKind == JsonValueKind.Array)
        {
            foreach (var session in sessionArray.EnumerateArray())
            {
                sessions.Add(new AudioSessionInfo(
                    session.GetStringOrNull("processName") ?? "",
                    session.TryGetProperty("processId", out var pid) &&
                    pid.ValueKind == JsonValueKind.Number ? pid.GetInt32() : 0,
                    session.GetStringOrNull("displayName") ?? "",
                    session.GetBoolOrFalse("isSystemSound"),
                    session.GetStringOrNull("state")));
            }
        }

        return new DeviceRouting(
            deviceId,
            role,
            ChannelExtensions.FromJsonKey(role), // "stream"/"none" resolve to null, by design
            dataFlow.Value,
            sessions);
    }
}